// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSnya5kBzSopdcgSen8FPV_Km9KHeOHWk',
    appId: '1:199209182633:web:14b5979989ff38db16d0b8',
    messagingSenderId: '199209182633',
    projectId: 'sg-scholars-guide-dev',
    authDomain: 'sg-scholars-guide-dev.firebaseapp.com',
    storageBucket: 'sg-scholars-guide-dev.appspot.com',
    measurementId: 'G-EXS96HXGG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQzPGcO-Wkqaryc8aiASBGC0bLlhgeiJw',
    appId: '1:199209182633:android:d710e4814d4df6bf16d0b8',
    messagingSenderId: '199209182633',
    projectId: 'sg-scholars-guide-dev',
    storageBucket: 'sg-scholars-guide-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3A4ITrIL8yIlBl4dHTEkNVdv5_wflH-E',
    appId: '1:199209182633:ios:8a0575f8a09631ee16d0b8',
    messagingSenderId: '199209182633',
    projectId: 'sg-scholars-guide-dev',
    storageBucket: 'sg-scholars-guide-dev.appspot.com',
    iosBundleId: 'com.nesvier.scholarsGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3A4ITrIL8yIlBl4dHTEkNVdv5_wflH-E',
    appId: '1:199209182633:ios:a5c3b12c74d06b8916d0b8',
    messagingSenderId: '199209182633',
    projectId: 'sg-scholars-guide-dev',
    storageBucket: 'sg-scholars-guide-dev.appspot.com',
    iosBundleId: 'com.nesvier.scholarsGuide.RunnerTests',
  );
}
